version: '3'
services:

#-------------------------#

  dummy-sensor-data:
    image: waziup/dummy-sensor-data:latest
    container_name: waziup.dummy-sensor-data
    build:
      context: ./
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./:/root/app
    privileged: false
    healthcheck:
      test: curl --fail --unix-socket /root/app/proxy.sock http://localhost/ || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes      
    restart: always

#-------------------------#
